### DISCUSSION TITLE
I would like to call Tweego to compile my .tw files and deploy the HTML file to a GitHub page using a build.yml action - but I am having difficulty using "go get github.com/tmedwards/tweego".

### DISCUSSION THREAD

**Discussion by Elleynn** [tmedwards/tweego#59] [Q&A]
I would first like to acknowledge that I am a relative newcomer to pretty much all of this: GitHub, Go, Twine, Tweego, etc... So the possibility that I am just majorly mucking up something is very much non-zero. 

That being said, I have been following a few tutorials on compiling and deploying a twine game to a GitHub page through the use of a GitHub action - and having no luck actually implementing the instructions. The two tutorials I followed were from:
**LazerWalker** - https://dev.to/lazerwalker/a-modern-developer-s-workflow-for-twine-4imp
and 
**6notes** - https://6notes.github.io/blog/notes/jkoetciw8gx345vhbipiijy/

My problem is primarily with "getting" Tweego and using it to compile my files. I've discovered that the tutorials themselves seem to have depreciated in the last year or so - as such even forking the TweeExample repository from 6notes results in the same build failures.
![builderror](https://github.com/tmedwards/tweego/assets/165116997/08367856-0805-4d2f-85d5-cbb99face1a2)

package golang.org/x/text/unicode/norm: found packages norm (composition.go) and main (maketables.go) in /home/runner/go/src/golang.org/x/text/unicode/norm
Error: Process completed with exit code 1.
Is the specific error I am getting after calling "go get github.com/tmedwards/tweego"

I'm also including my build.yml file in hopes that someone may catch something that I am not understanding.

```
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.13'
          
      - name: build game
        run: |
          go get github.com/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir -p ${{vars.OUTPUT_DIRECTORY}} && touch ${{vars.OUTPUT_DIRECTORY}}/${{vars.OUTPUT_FILENAME}}
          tweego ./src -o ${{vars.OUTPUT_DIRECTORY}}/${{vars.OUTPUT_FILENAME}}

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: ./${{vars.OUTPUT_DIRECTORY}}/
```

I have tried using other version of Go to see if it will compile, but none of those runs build successfully either. If you would like a good example of the workflow I am trying to implement, I would look at [6note's blog](https://6notes.github.io/blog/notes/jkoetciw8gx345vhbipiijy/) and their [TweeExample repository.](https://github.com/6notes/tweeExample)

If anyone can see where I might be going wrong, or has an alternative that may work instead, I would be very grateful!
